user_database_name = "UserDB.parquet"
anime_database_name = "AnimeDB.parquet"
MAL_users_filename = "MALUsers.csv"
blacklist_users_filename = "Blacklist.csv"
scores_dict_filename = "ScoresDBDict.pickle"
aff_db_filename = "AffinityDB"
# The lack of extension is on purpose ^
entry_tags_filename = "entry_tags_dict.pickle"
shows_tags_filename = "shows_tags_dict.pickle"
graphs_dict_filename = "all_graphs.pickle"
relations_dict_filename = "anime_relations.pickle"
