# Generated by Django 4.2.5 on 2024-01-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animedata_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
