# Generated by Django 4.2.5 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_animedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animedata',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='episodes',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='mal_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='mean_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='scores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='season',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animedata',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animedata',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
