# Generated by Django 4.2.5 on 2024-01-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_animedata_duration_animedata_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animedata',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='episodes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='season',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animedata',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
