# Generated by Django 4.2.5 on 2024-03-12 11:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usernamecache'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animedata',
            managers=[
                ('objects_with_retry', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taskqueue',
            managers=[
                ('objects_with_retry', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usernamecache',
            managers=[
                ('objects_with_retry', django.db.models.manager.Manager()),
            ],
        ),
    ]
