# Generated by Django 4.2.5 on 2024-08-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_usernamecache_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskQueue',
        ),
        migrations.DeleteModel(
            name='UsernameCache',
        ),
    ]
