# Generated by Django 4.2.5 on 2025-01-14 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_taskqueue_delete_usernamecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
